In [14]:
import cv2
import numpy as np

arr = np.ones([450,600,3])*255
arr[:,:,1] -= np.arange(600)/5
arr[:,:,0] = np.arange(600)/5
cv2.imwrite('orange_yel.jpg',arr)
print(arr)

[[[0.000e+00 2.550e+02 2.550e+02]
  [2.000e-01 2.548e+02 2.550e+02]
  [4.000e-01 2.546e+02 2.550e+02]
  ...
  [1.194e+02 1.356e+02 2.550e+02]
  [1.196e+02 1.354e+02 2.550e+02]
  [1.198e+02 1.352e+02 2.550e+02]]

 [[0.000e+00 2.550e+02 2.550e+02]
  [2.000e-01 2.548e+02 2.550e+02]
  [4.000e-01 2.546e+02 2.550e+02]
  ...
  [1.194e+02 1.356e+02 2.550e+02]
  [1.196e+02 1.354e+02 2.550e+02]
  [1.198e+02 1.352e+02 2.550e+02]]

 [[0.000e+00 2.550e+02 2.550e+02]
  [2.000e-01 2.548e+02 2.550e+02]
  [4.000e-01 2.546e+02 2.550e+02]
  ...
  [1.194e+02 1.356e+02 2.550e+02]
  [1.196e+02 1.354e+02 2.550e+02]
  [1.198e+02 1.352e+02 2.550e+02]]

 ...

 [[0.000e+00 2.550e+02 2.550e+02]
  [2.000e-01 2.548e+02 2.550e+02]
  [4.000e-01 2.546e+02 2.550e+02]
  ...
  [1.194e+02 1.356e+02 2.550e+02]
  [1.196e+02 1.354e+02 2.550e+02]
  [1.198e+02 1.352e+02 2.550e+02]]

 [[0.000e+00 2.550e+02 2.550e+02]
  [2.000e-01 2.548e+02 2.550e+02]
  [4.000e-01 2.546e+02 2.550e+02]
  ...
  [1.194e+02 1.356e+02 2.550e+02]
  [1

In [15]:
arr = arr.astype(np.float32)/255 # normalize to 0->1
teto = cv2.imread('teto.jpg').astype(np.float32)

teto2 = cv2.multiply(teto,arr)
cv2.imwrite('teto_shaded_dinner.jpg',teto2)

True