In [1]:
import cv2
import numpy as np

rup1 = np.tile(np.arange(256), (256,1))
rup2 = rup1.T
cv2.imwrite('im1.png', rup1)
cv2.imwrite('im2.png', rup2)

True

In [6]:
a = np.arange(5)
print(a)

[0 1 2 3 4]


In [7]:
b = np.tile(a, 2)
print(b)

[0 1 2 3 4 0 1 2 3 4]


In [12]:
c = np.tile(a, (5,5))
print(c)

[[0 1 2 3 4 0 1 2 3 4 0 1 2 3 4 0 1 2 3 4 0 1 2 3 4]
 [0 1 2 3 4 0 1 2 3 4 0 1 2 3 4 0 1 2 3 4 0 1 2 3 4]
 [0 1 2 3 4 0 1 2 3 4 0 1 2 3 4 0 1 2 3 4 0 1 2 3 4]
 [0 1 2 3 4 0 1 2 3 4 0 1 2 3 4 0 1 2 3 4 0 1 2 3 4]
 [0 1 2 3 4 0 1 2 3 4 0 1 2 3 4 0 1 2 3 4 0 1 2 3 4]]


In [14]:
cv2.imwrite('im4.png',rup1-rup2)

True

In [21]:
rup3 = np.ones([256,256,3])*255
# print(rup3)
rup3[:,:,0] = 0
# print(rup3)
rup3[:,:,1] = np.arange(256)
print(rup3)
cv2.imwrite('im_1_red2yel.png',rup3)

True

In [28]:
rup4 = np.zeros([256,256,3])
rup4[:,:,0] = 255
rup4[:,:,1] = np.arange(256).reshape(256,1)
cv2.imwrite('im_1_blue2sky.png',rup4)
print(rup4)

[[[255.   0.   0.]
  [255.   0.   0.]
  [255.   0.   0.]
  ...
  [255.   0.   0.]
  [255.   0.   0.]
  [255.   0.   0.]]

 [[255.   1.   0.]
  [255.   1.   0.]
  [255.   1.   0.]
  ...
  [255.   1.   0.]
  [255.   1.   0.]
  [255.   1.   0.]]

 [[255.   2.   0.]
  [255.   2.   0.]
  [255.   2.   0.]
  ...
  [255.   2.   0.]
  [255.   2.   0.]
  [255.   2.   0.]]

 ...

 [[255. 253.   0.]
  [255. 253.   0.]
  [255. 253.   0.]
  ...
  [255. 253.   0.]
  [255. 253.   0.]
  [255. 253.   0.]]

 [[255. 254.   0.]
  [255. 254.   0.]
  [255. 254.   0.]
  ...
  [255. 254.   0.]
  [255. 254.   0.]
  [255. 254.   0.]]

 [[255. 255.   0.]
  [255. 255.   0.]
  [255. 255.   0.]
  ...
  [255. 255.   0.]
  [255. 255.   0.]
  [255. 255.   0.]]]


In [29]:
cv2.imwrite('addition.png',cv2.add(rup3,rup4))
cv2.imwrite('subtract1.png',cv2.subtract(rup3,rup4))
cv2.imwrite('substact2.png',cv2.subtract(rup4,rup3))

True